apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: quarkus-pipeline-run
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/seedwing-io/seedwing-java-example'
    - name: GIT_REVISION
      value: main 
    - name: DOCKERFILE
      value: src/main/docker/Dockerfile.jvm
    - name: BUILDER_IMAGE
      value: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
    - name: IMAGE
      value: 192.168.1.2:5001/seedwing-java-example:latest
  pipelineRef:
    name: quarkus-pipeline
  serviceAccountName: default
  timeout: 1h0m0s
  taskRunSpecs:
    - pipelineTaskName: kaniko-build
      taskPodTemplate:
        imagePullSecrets:
          - name: registry-credentials
  workspaces:
    - name: dockerconfig
      secret:
        secretName: registry-credentials
    - name: build
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
