apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-pipeline
spec:
  params:
    - description: Git repository
      name: GIT_REPO
      type: string
    - name: GIT_REVISION
      description: Git revision to checkout
      default: main
    - default: .
      name: PROJECT_PATH
      description: Path to project to build
      type: string
    - default: Dockerfile
      name: DOCKERFILE
      description: Path to Dockerfile
      type: string
    - name: BUILDER_IMAGE
      description: Java builder image
      type: string
      default: registry.access.redhat.com/ubi8/openjdk-17:latest
    - description: Image to build
      name: IMAGE
      type: string
    - name: SEEDWING_IMAGE
      description: The seedwing image
      default: ghcr.io/seedwing-io/swio:0.1.0-nightly.38acce4f
  tasks:
    # Clone the repository
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    # Build the quarkus application
    - name: quarkus-build
      params:
        - name: PROJECT_PATH
          value: $(params.PROJECT_PATH)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: quarkus-build
      workspaces:
        - name: build
          workspace: source
    # Build the container image and add build attestations
    - name: kaniko-build
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: CONTEXT
          value: $(workspaces.source.path)/$(params.PROJECT_PATH)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      runAfter:
        - quarkus-build
      taskRef:
        kind: Task
        name: kaniko-chains
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig

    # Verify that build attestations and company policies are approved
    - name: seedwing
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: SEEDWING_IMAGE
          value: $(params.SEEDWING_IMAGE)
        - name: PROJECT_PATH
          value: $(params.PROJECT_PATH)
      runAfter:
        - kaniko-build
      taskRef:
        kind: Task
        name: seedwing-eval
      workspaces:
        - name: source
          workspace: source
        - name: policies
          workspace: policies
  workspaces:
    - name: source
    - name: dockerconfig
    - name: policies
